[package]
name = "trust"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[dependencies]
tun-tap = "0.1.2"
etherparse = "0.8"
bitflags = "1.0"
nix = "0.13"

[lib]
name = "trust"

[[bin]]
name = "trust"
